-- Complete database setup for Harivillu Ventures website
-- Run this in your Supabase SQL Editor

-- Create projects table (if not exists)
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  images json null,
  title text null,
  description text null,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;

-- Create form submissions table (if not exists)
CREATE TABLE IF NOT EXISTS public.form (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  name text null,
  phone text null,
  subject text null,
  message text null,
  constraint form_pkey primary key (id)
) TABLESPACE pg_default;

-- Disable RLS for both tables (for easier development)
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.form DISABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.form TO anon, authenticated;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_form_created_at ON public.form(created_at DESC);

-- Insert sample projects (optional)
INSERT INTO public.projects (title, description, images) VALUES
(
  'Premium Gated Community',
  'A premium gated community with lush green parks and modern amenities. Features include 24/7 security, clubhouse, swimming pool, and children''s play area.',
  '["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&h=600&fit=crop"]'
),
(
  'Commercial Development Hub',
  'Prime commercial land ideal for business and investment opportunities. Located in the heart of the business district with excellent connectivity.',
  '["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1460472178825-e5240623afd5?w=800&h=600&fit=crop"]'
),
(
  'Luxury Villa Enclave',
  'Modern villas with contemporary architecture and landscaped gardens. Each villa comes with private parking, garden space, and premium finishes.',
  '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop"]'
),
(
  'Eco-Friendly Township',
  'Sustainable living with rainwater harvesting, solar lighting, and green spaces. A perfect blend of modern amenities and environmental consciousness.',
  '["https://images.unsplash.com/photo-1564013434775-cb28cc6b50b5?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop"]'
);

-- Verification queries
SELECT 'Projects created:' as status, COUNT(*) as count FROM public.projects;
SELECT 'Form submissions:' as status, COUNT(*) as count FROM public.form;

-- Show recent projects
SELECT id, title, description, created_at FROM public.projects ORDER BY created_at DESC LIMIT 5;
