-- Supabase SQL Setup for Contact Form Submissions
-- Run this query in your Supabase SQL Editor

-- Create the form submissions table
CREATE TABLE public.form (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  name text null,
  phone text null,
  subject text null,
  message text null,
  constraint form_pkey primary key (id)
) TABLESPACE pg_default;

-- Enable Row Level Security (RLS) for better security
ALTER TABLE public.form ENABLE ROW LEVEL SECURITY;

-- Create policies for the form table
-- Allow anyone (including anonymous) to insert (so contact form works)
CREATE POLICY "Allow anonymous insert" ON public.form
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Allow authenticated users to view all submissions (for admin panel)
CREATE POLICY "Allow authenticated select" ON public.form
  FOR SELECT TO authenticated USING (true);

-- Allow authenticated users to delete submissions (for admin panel)
CREATE POLICY "Allow authenticated delete" ON public.form
  FOR DELETE TO authenticated USING (true);

-- Grant necessary permissions
GRANT SELECT, INSERT, DELETE ON public.form TO anon, authenticated;

-- Create an index for better performance on created_at column
CREATE INDEX idx_form_created_at ON public.form(created_at DESC);

-- Verification query (optional - run to check if table was created)
-- SELECT * FROM public.form ORDER BY created_at DESC LIMIT 5;
