-- Create projects table and fix RLS issues
-- Run this in your Supabase SQL Editor

-- Create the projects table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  images json null,
  title text null,
  description text null,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;

-- Disable RLS for both tables
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.form DISABLE ROW LEVEL SECURITY;

-- Grant full permissions to both anon and authenticated users
GRANT ALL ON public.projects TO anon, authenticated;
GRANT ALL ON public.form TO anon, authenticated;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_form_created_at ON public.form(created_at DESC);

-- Test insert to make sure everything works
INSERT INTO public.projects (title, description, images) VALUES
('Test Project', 'This is a test project to verify the setup', '["https://via.placeholder.com/400x300"]')
ON CONFLICT DO NOTHING;

-- Verify the setup
SELECT 'Projects table created successfully' as status;
SELECT COUNT(*) as project_count FROM public.projects;
SELECT COUNT(*) as form_count FROM public.form;
