-- Quick fix for projects table RLS issues
-- Run this in your Supabase SQL Editor

-- First, create the table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  images json null,
  title text null,
  description text null,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow anonymous select" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.projects;

-- Temporarily disable RLS for testing
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;

-- Grant permissions to both anon and authenticated users
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO anon, authenticated;

-- Create an index for better performance
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);

-- Test the table
SELECT COUNT(*) as total_projects FROM public.projects;
