-- Supabase SQL Setup for Projects Table
-- Run this query in your Supabase SQL Editor

-- Create the projects table (if not already created)
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  images json null,
  title text null,
  description text null,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;

-- Enable Row Level Security (RLS) for the projects table
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow anonymous select" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.projects;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.projects;

-- Create policies for the projects table
-- Allow anyone to view projects (for the Projects page)
CREATE POLICY "Allow anonymous select" ON public.projects
  FOR SELECT TO anon, authenticated USING (true);

-- Allow authenticated users to insert projects (for admin panel)
CREATE POLICY "Allow authenticated insert" ON public.projects
  FOR INSERT TO authenticated WITH CHECK (true);

-- Allow authenticated users to update projects (for admin panel)
CREATE POLICY "Allow authenticated update" ON public.projects
  FOR UPDATE TO authenticated USING (true);

-- Allow authenticated users to delete projects (for admin panel)
CREATE POLICY "Allow authenticated delete" ON public.projects
  FOR DELETE TO authenticated USING (true);

-- Grant necessary permissions
GRANT SELECT ON public.projects TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.projects TO authenticated;

-- Create an index for better performance on created_at column
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);

-- Verification query (optional - run to check if table was created)
SELECT COUNT(*) as total_projects FROM public.projects;
SELECT * FROM public.projects ORDER BY created_at DESC LIMIT 5;
